### ISSUE TITLE
Revert non-ASCII fix when fixed in source.

### ISSUE THREAD

**Issue by busykoala** [4teamwork/ftw.lawgiver#98]
When https://github.com/plone/plone.app.content/pull/191 is merged we can revert https://github.com/4teamwork/ftw.lawgiver/pull/97 and allow non-ASCII characters again.

**Comment by jone** [comment]
The ftw.lawgiver fix can only be removed when we no longer have affected sites. This means when all Plone 5 sites are updated to a Plone 5 version which includes the fix.

**Comment by busykoala** [comment]
This was done in https://github.com/4teamwork/ftw.lawgiver/pull/99
